// cookie fortunes for mahjong.js

var fortunes = [
  "A bird in the hand can be messy.",
  "Add to your understanding of foreign art and culture.",
  "Alas! The onion you are eating is someone else's water lily.",
  "An aura of glamour and mystery surrounds your events of the week.",
  "An emptiness soon will be filled.",
  "An important visitor will vow complete support.",
  "Anyone who makes a blanket statement is a fool.",
  "Avert misunderstandings by calm, poise and balance.",
  "Avoid taking unnecessary gambles.",
  "Be the first to try something new.",
  "Confucius say: Angel with wings not so hot as angel with arms.",
  "Confucius say: This cookie no good.",
  "Confucius say: You have heart as big as Texas.",
  "Confucius say: make sure words touch wisdom tooth on way out of mouth.",
  "Don't ask, don't say. Everything lies in sillence.",
  "Encouraging changes are not advertised on TV.",
  "Everything is not yet lost.",
  "Find release from your cares have a good time.",
  "Finding exotic uses for what others ignore will make your special fortune.",
  "Generosity and perfection are your everlasting goals.",
  "Genius does what it must, cameras do what they can.",
  "Good news will come to you from close at hand.",
  "Good news will come to you from far away.",
  "Happiness and good fortune will come to you soon.",
  "He asks advice in vain who will not follow it.",
  "He who has imagination without learning has wings but no feet.",
  "Hell is paved with good intentions.",
  "Helping others can become a satisfying way of life.",
  "Hope for the best, but prepare for the worst.",
  "How you look depends on where you go.",
  "Idleness is the holiday of fools.",
  "If it wasn't for the last minute, nothing would get done.",
  "If justice rules the universe, we are all in trouble.",
  "If you can shape it in your mind, you will find it in your life.",
  "It's easier to curse a candle than to light the darkness.",
  "Keep your schedule flexible to handle the unexpected.",
  "Life's reward will be yours.",
  "Live each day to the fullest.",
  "Love will come looking for you.",
  "Malice is stupidity raised to a higher power.",
  "Now is a good time to start something new.",
  "Now it is best to approach things just one step at a time.",
  "Pray for what you want; but work for what you need.",
  "Prayers are always answered eventually.",
  "Pressure from a mouse should not sway your decision.",
  "Reduce to a minimum what is necessary in your fish bowl.",
  "Save now for future calamities.",
  "Someone is speaking well of you.",
  "Someone thinks you are very special and lets you know it.",
  "Sweet Memories are the water cooler of the mind.",
  "The most important things in life are not things.",
  "The next cookie fortune you read will be better than this one.",
  "The only constant since the beginning of time is change.",
  "The path to enlightenment requires open eyes and willing feet.",
  "The sooner you get behind, the more time you'll have to catch up.",
  "There ain't no such thing as a free lunch ... unless you own the restaurant.",
  "There is a great tempteation in store for your potato chips.",
  "There is no way of judging the future but by the past.",
  "There is yet time enough for you to take a different path.",
  "This is really a lovely day. Congratulations.",
  "Those who speak loudest always have the least to say.",
  "Time exists solely to prevent everything from happening at once.",
  "To err is human, to forgive ... unlikely.",
  "To see others, you must only watch; to see yourself, you must look.",
  "Too much confidence has deceived many a one.",
  "Wise men learn much from fools.",
  "You are almost there.",
  "You are bright.  So give out that light!",
  "You are entering a time of great promise and overdue rewards.",
  "You are interested in public service and would make an outstanding statesman.",
  "You are more likely to give than get a cold wet nose on your leg.",
  "You have an optimistic outlook on life, for very good reason.",
  "You have many personal talents that are attractive to others.",
  "You have the ability to make lifelong friends.",
  "You may attend a party where strange customs prevail.",
  "You should be pleased with answers you are given now.",
  "You will be advanced socially, without any special effort on your part.",
  "You will be fortunate in everything you put your hands to.",
  "You will be fortunate in the opportunities presented to you.",
  "You will be showered with good luck.",
  "You will get help from an influential friend.",
  "You will meet an important person who will help you advance professionally.",
  "You will receive a favor or kindness from someone.",
  "You will soon gain something you have always wanted.",
  "You will succeed, but wait for the opportune moment.",
  "Your energy is at a peak.  Channel it into fun activities.",
  "Your future is as boundless as the lofty heaven.",
  "Your future will be easier to digest than this cookie.",
];

// eof;
